name = "smart-fridge-edge-gateway"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[vars]
ENVIRONMENT = "production"
# Secrets such as TELEGRAM_BOT_TOKEN are set via `wrangler secret put TELEGRAM_BOT_TOKEN`

[[kv_namespaces]]
binding = "FRIDGE_KV"
id = "229245076f964611ae2b95aa6d6db11a"

[[d1_databases]]
binding = "DB"
database_name = "smart-fridge-db"
database_id = "c448cffa-f1a3-463d-bd9c-f476eb16c486"

[triggers]
crons = ["0 6 * * *"] # 06:00 UTC = 09:00 MSK ежедневно (или каждые 30 минут)


